"""empty message

Revision ID: 3e20914e232d
Revises: 757c10e31bb5
Create Date: 2019-10-03 18:07:54.456580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e20914e232d'
down_revision = '757c10e31bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=40), nullable=False),
    sa.Column('is_first', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['click_id'], ['click.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_timestamp'), 'action', ['timestamp'], unique=False)
    op.drop_table('program')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_action_timestamp'), table_name='action')
    op.drop_table('action')
    op.drop_table('click')
    # ### end Alembic commands ###
