"""Site model

Revision ID: 757c10e31bb5
Revises: 7b0977a55b5a
Create Date: 2019-09-30 23:21:08.042898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757c10e31bb5'
down_revision = '7b0977a55b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('hash_str', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_str')
    )
    op.create_index(op.f('ix_link_timestamp'), 'link', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_timestamp'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
