"""empty message

Revision ID: cbc29522a9d0
Revises: 
Create Date: 2019-10-04 12:32:54.016475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc29522a9d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=40), nullable=False),
    sa.Column('is_first', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('messenger_type', sa.String(), nullable=True),
    sa.Column('messenger', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_messenger_type'), 'user', ['messenger_type'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('hash_str', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_str')
    )
    op.create_index(op.f('ix_link_timestamp'), 'link', ['timestamp'], unique=False)
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['click_id'], ['click.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_timestamp'), 'action', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_timestamp'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_link_timestamp'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_user_messenger_type'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('click')
    # ### end Alembic commands ###
